# yaml-language-server: $schema=https://github.com/oapi-codegen/oapi-codegen/raw/refs/heads/main/configuration-schema.json
package: server
output: zz_generated.server.go
generate:
  chi-server: true
  embedded-spec: true
